#Workflow Name
name: Github Actions Schedule

#Trigger on which should workflow run
on:
   #List of Schedules when Workflow should run
   schedule:
       - cron: "0/5 * * * *"

#Jobs to run when workflow is triggered
jobs:
    #Name of the job
    run-linux-commands:
       #Runs on runner provided by Github
       runs-on: ubuntu-latest
       #Steps involved in job
       steps:
            #Name of the step
          - name: Linux File Commands
            #Commands to run in step
            run: |
                 pwd
                 ls
